# Generated by Django 5.0.4 on 2024-04-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tweetauthor',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
