# Generated by Django 5.0.4 on 2024-04-04 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_alter_tweet_id_alter_tweetauthor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetauthor',
            name='description',
        ),
    ]
