# Generated by Django 5.0.4 on 2024-04-04 05:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0003_remove_tweetauthor_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TweetHashtag",
        ),
    ]
