# Generated by Django 5.0.4 on 2024-04-04 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0005_alter_tweet_tweet"),
    ]

    operations = [
        migrations.CreateModel(
            name="TweetHashtag",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("hashtag", models.CharField(max_length=256)),
                (
                    "tweet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tweets.tweet"
                    ),
                ),
            ],
        ),
    ]
