# Generated by Django 5.0.4 on 2024-04-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_alter_tweethashtag_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='hashtags',
            field=models.ManyToManyField(to='tweets.tweethashtag'),
        ),
    ]
