# Generated by Django 5.0.4 on 2024-04-05 05:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0009_tweet_hashtags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="hashtags",
        ),
    ]
